application:
  name: strapi
  project: strapi
  cloud_region: aws/us-east-2
  publicly_accessible: true
    #  storage:
    #    - name: data
    #      type: ssd
    #      size: 10GB
    #      mount_point: /srv/app
databases:
- type: postgresql
  version: "11"
  name: my-psql
routers:
- name: main
  custom_domains:
  - branch: master
    domain: strapi.qvy.io
  routes:
  - application_name: strapi
    paths:
    - /*

