application:
  name: strapi
  project: strapi
  cpu: 512m
  memory: 512mb
  publicly_accessible: true
    #  storage:
    #    - name: data
    #      type: ssd
    #      size: 10GB
    #      mount_point: /srv/app
databases:
- type: postgresql
  version: 12
  name: my-psql
routers:
- name: main
  custom_domains:
  - branch: master
    domain: strapi.qvy.io
  routes:
  - application_name: strapi
    paths:
    - /*

