application:
  name: strapi
  project: strapi
  cloud_region: aws/us-east-2
  publicly_accessible: true
databases:
- type: postgresql
  version: "11"
  name: my-psql
routers:
- name: main
  routes:
  - application_name: strapi
    paths:
    - /*
