application:
  name: strapi
  project: strapi
  cpu: 800m
  ram: 512mb
  start_timeout: 60s
  publicly_accessible: true
  storage:
    - name: data
      type: ssd
      size: 10GB
      mount_point: /srv/app
  depends_on:
  - frontend1
  - frontend2
databases:
- type: postgresql
  version: 12
  name: my-psql
routers:
- name: main
  custom_domains:
  - branch: master
    domain: strapi.qvy.io
  routes:
  - application_name: strapi
    paths:
    - /*

